# Пользователи
## Создать нового пользователя

POST http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "TOR@overlook.net",
  "name": "Jack123",
  "avatar": "avatar.png",
  "pol": "Женский",
  "user_type": "Тренер",
  "about_me": "Просто хорорший человек",
  "location": "Петроградская",
  "image_page": "image.jpg",
  "password": "shining"
}

###

## Авторизовать пользователя

POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "TOR@overlook.net",
  "password": "shining"
}

###
## Проверить токен пользователя
GET http://localhost:4000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IlRPUkBvdmVybG9vay5uZXQiLCJmaXJzdG5hbWUiOiJKYWNrMTIzIiwiaWQiOiI2NWQxZWI4ZGYxNzQxYWQ1NzllNzQ5ZDQiLCJpYXQiOjE3MDgyNTYxNDUsImV4cCI6MTcwODQyODk0NX0.4iGBlbvlHoorxMYG1X1K324viKZknIPsZqbtouj6B1o
