# Пользователи

# Получить список пользователей (только авторизированные)
GET http://localhost:4000/users HTTP/1.1
Content-Type: application/json
###

# Создать нового пользователя
POST http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "TOR@overlook.net",
  "name": "Jack123",
  "avatar": "avatar.png",
  "pol": "Женский",
  "user_type": "Тренер",
  "about_me": "Просто хорорший человек",
  "location": "Петроградская",
  "image_page": "image.jpg",
  "password": "shining"
}

###

## Авторизовать пользователя

POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "TOR@overlook.net",
  "password": "shining"
}

###


## Проверить токен пользователя
GET http://localhost:4000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IlRPUkBvdmVybG9vay5uZXQiLCJuYW1lIjoiVmVyYSIsImlkIjoiNjYwNmEwOWI3ZGEwYTJlZThhZTZlNTkxIiwiaWF0IjoxNzExODE1MTQ1LCJleHAiOjE3MTE5ODc5NDV9.ViCpylo60nYJaftUCjhZv6VRhzmaiL5D3KLKm7wK6ts


###

# Получить детальную информацию по пользователю (могут все)
GET http://localhost:4000/users/65530e30a6380c83ba723099 HTTP/1.1

###


## Редактирование информации о пользователе (только свои)

PATCH http://localhost:4000/users/6606a09b7da0a2ee8ae6e591 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IlRPUkBvdmVybG9vay5uZXQiLCJuYW1lIjoiVmVyYSIsImlkIjoiNjYwNmEwOWI3ZGEwYTJlZThhZTZlNTkxIiwiaWF0IjoxNzExODE1MTQ1LCJleHAiOjE3MTE5ODc5NDV9.ViCpylo60nYJaftUCjhZv6VRhzmaiL5D3KLKm7wK6ts

{
  "name": "Veera"
}

